genres = ['RPG',
          'Simulation',
          'Table Game',
          'Action',
          'Adventure',
          'Shooter',
          'Action RPG',
          'Racing',
          'Online RPG',
          'Online Sim',
          'Trivia',
          'Life Sim',
          'Board Game',
          'Puzzle',
          'Music Game',
          'Audio Novel',
          'Motion Game',
          'Educational',
          'Sim RPG',
          'Card Game',
          'Sports']

types = ['Exploration',
         'Martial Arts',
         'Fantasy',
         'Virtual Pet',
         'Samurai',
         'Dungeon',
         'Romance',
         'Pirate',
         'Comedy',
         'Horror',
         'Word',
         'Train',
         'Animal',
         'Robot',
         'Space',
         'Airplane',
         'Conv. Store',
         'Historical',
         'Bookstore',
         'Comics',
         'Art',
         'Movies',
         'Game Co.',
         'Egypt',
         'Town',
         'Architecture',
         'Lawyer',
         'Medieval',
         'Monster',
         'Hunting',
         'High School',
         'Junior High',
         'War',
         'Ninja',
         'Cutie',
         'Ogre',
         'Fashion',
         'Detective',
         'Mystery',
         'Cowboy',
         'Horseshoes',
         'President',
         'Stocks',
         'Cartoon',
         'Cosplay',
         'Pop Star',
         'Swimsuit',
         'Mini-skirt',
         'Mushroom',
         'Poncho',
         'Chess',
         'Checkers',
         'Mahjong',
         'Reversi',
         'Dance',
         'Drums',
         'Fitness',
         'Wrestling',
         'Jumprope',
         'Basketball',
         'Skiing',
         'Snowboard',
         'Golf',
         'Swimming',
         'Volleyball',
         'Motorsport',
         'Soccer',
         'Ping Pong',
         'Sumo',
         'Baseball',
         'Wrestling',
         'Marathon',
         'F1 Racing',
         'Pinball',
         'Slots',
         'Dating',
         'Harbor',
         'Time Travel',
         'Spy',
         'Celebrity']

import random as rnd

print 'GAME IDEAS'
print
print
for i in range(10):
    print '%s %s' % (rnd.choice(types),
                     rnd.choice(genres))
    print
