from util import *

# CARDS
CARDWIDTH = 112
CARDHEIGHT = 160

ZOOMEDCARDWIDTH = 336
ZOOMEDCARDHEIGHT = 480

CARDBACKIMAGE = "Images/cardBack.jpg"
DRAINEDDOMAINIMAGE = "Images/patternCardBack.jpg"

RESOURCEBAR = CARDHEIGHT//10



# HANDS
HANDMAXWIDTH = 224.
MAXHANDSTEP = 75
MINHANDSTEP = 20


# RIGHT PANEL (ZOOM WINDOW, HANDS, DISCARD PILE)
RIGHTPANELWIDTH = ZOOMEDCARDHEIGHT

# MIDDLE PANEL (STORIES)
SPACEBETWEENSTORIES = CARDHEIGHT // 4

# LEFT PANEL (DOMAINS)
DOMAINPANELWIDTH = CARDHEIGHT // 4
SPACEBETWEENDOMAINS = 3
DOMAINPANELVERTICALMARGIN = toInt (1.5 * CARDWIDTH)



